### ISSUE TITLE
Dependency on `mathcomp` unclear

### ISSUE THREAD

**Issue by wenkokke** [OUPL/OUVerT#6]
It seems like the OUVerT library dependens on mathcomp, but the exact versions of `coq-mathcomp-algebra` and `coq-mathcomp-ssreflect` it depends on are unclear. Using versions 1.10.0 for both, `make` emits a large number of warnings, then fails:

```
File "./numerics.v", line 870, characters 2-6:
Error: Attempt to save an incomplete proof (in proof rat_to_R_0_center)
```

Using 1.7.0 for both, `make` works, although it still emits all the warnings.

**Comment by david-masters** [comment]
It requires 1.7.0. I just updated the README to reflect this. I've been working on reducing the warnings, they should be mostly or completely gone in the near future.

**Comment by wenkokke** [comment]
Thanks!
